# Generated by Django 4.2.2 on 2023-07-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pole',
            field=models.CharField(default='', max_length=55),
        ),
    ]
