# Generated by Django 4.2.3 on 2023-08-20 14:17

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='signin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='signin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='signin',
            name='username',
        ),
        migrations.AlterField(
            model_name='statustask',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
