# Generated by Django 4.2.2 on 2023-07-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_user_pole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pole',
        ),
    ]
