# Generated by Django 4.2.2 on 2023-07-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_user_pole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=55),
        ),
    ]
